services:
  api:
    image: dockeromer/job-vault-api:latest
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    networks:
      - app-network

  web:
    image: dockeromer/job-vault-web:latest
    ports:
      - "8100:8100"
    networks:
      - app-network
    environment:
      - NODE_ENV=development
    stdin_open: true
    tty: true

networks:
  app-network:
    driver: bridge
