spring:
  application:
    name: job-vault
  datasource:
    url: jdbc:h2:mem:candidatedb
    username: sa
    password: ""
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    show-sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
logging:
  level:
    root: debug

